# New Section

In [1]:
import numpy as np

In [2]:


s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])



In [6]:
b= np.sum(s,axis=1)
for i in b:
  if i !=45:
    print("sudoko  is not correct")
else:
  print("sudoko is  correct")

sudoko is  correct


In [8]:
a = np.sum(s, axis=0)
for i in a:
  if i != 45:
    print("sudoko  is not correct")
else:
  print("sudoko is  correct")
#

sudoko is  correct


In [22]:
g = s[0:3,0:3]
if np.sum(g) == 45:
  print("sudoko is correct")
else:
  print("sudoko is not correct")

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [24]:
l=s[0:3,3:6]
if np.sum(l) == 45:
  print("sudoko is correct")
else:
  print("sudoko is not correct")

sudoko is correct


In [25]:
j = s[3:6,0:3]
if np.sum(j) == 45:
  print("sudoko is correct")    #here we can see that we can use for loop
  # for this as we have seen and we  don't have to use slicing again and again
else:
  print("sudoko is not correct")

sudoko is correct


In [26]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n = s[i:i+3,j:j+3]
    print(n.sum())
    if np.sum(n) == 45:
      print("sudoko is correct")
    else:
      print("sudoko is not correct")

45
sudoko is correct
45
sudoko is correct
45
sudoko is correct
45
sudoko is correct
45
sudoko is correct
45
sudoko is correct
45
sudoko is correct
45
sudoko is correct
45
sudoko is correct


In [31]:


import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])



In [34]:
#Get the shape of the matrix.
data.shape

#Find the average age of students.

#Extract Math marks of all students.

#Find the highest Science mark.

#Get details of the student who scored more than 90 in Math.

#Increase Math marks of all students by 5.

#Find how many students are younger than 19.

#Calculate the average marks in each subject (column-wise mean).

#Get data of students who scored at least 80 in both subjects.

#Replace all Science marks < 75 with 0.



(5, 3)

In [39]:
#Find the average age of students.
display(data[:, 0].mean())

np.float64(18.4)

In [40]:
display(data[:,1].sum())#Extract Math marks of all students.

np.int64(408)

In [41]:
display(data[:,2].max())#Find the highest Science mark.


np.int64(95)

In [50]:
#Get details of the student who scored more than 90 in Math.
for student in data:
  if student[1] >= 90:
    print(student)

[19 92 88]
[20 90 85]


In [52]:
#Increase Math marks of all students by 5.
data[:, 1] = data[:, 1] + 5
display(data)

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [53]:
#Find how many students are younger than 19.
for student in data:
  if student[0] < 19:
    print(student)

[18 90 78]
[17 81 95]
[18 70 70]


In [54]:
#Get data of students who scored at least 80 in both subjects.
for student in data:
  if student[1] >= 80 and student[2] >= 80:
    print(student)

[19 97 88]
[17 81 95]
[20 95 85]


In [55]:
#Replace all Science marks < 75 with 0.
for student in data:
  if student[2] < 75:
    student[2] = 0
display(data)

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])

In [56]:
#Calculate the average marks in each subject (column-wise mean)
for student in data:
  print(student.mean())


62.0
68.0
64.33333333333333
29.333333333333332
66.66666666666667
